### ISSUE TITLE
Feature request : distinct opacity for black bar

### ISSUE THREAD

**Issue by ChameleonScales** [wavexx/screenkey#47]
The black bar is cluttering my screen and the program I am screencasting on already has a dark interface.
Would it be possible to tweak its opacity independently from the characters or simply have a checkbox to disable it ?

**Comment by wavexx** [comment]
On Mon, Jul 03 2017, Caetano Veyssières wrote:
> The black bar is cluttering my screen and the program I am
> screencasting already has a dark interface. Would it be possible to
> tweak its opacity independently from the characters

I remember I tried, but AFAIK it was contrived to do with GTK.
I completely agree on the function though, and setting an independent
opacity is the way to go.

For future reference, this requires a cairo RGBA drawable on the label
manager, so that alpha can be set per-pixel. By rendering on it directly
directly with pango, we would allow also for inline images (ie: inline
mouse actions).

> or simply have a checkbox to disable it ?

We cannot do this currently.
We just set the transparency per-window.
