### ISSUE TITLE
Quit command?

### ISSUE THREAD

**Issue by i5ar** [wavexx/screenkey#50]
I can only use screenkey from the terminal (without slop) and I can't find a command to quit the program. So I have to kill the process every time.
Is there a better and faster way that I'm missing?

**Comment by wavexx** [comment]
On Tue, Aug 08 2017, iSar wrote:
> I can only use screenkey from the terminal (without slop) and I can't find a command to
> quit the program. So I have to kill the process every time.
> Is there a better and faster way that I'm missing?

I use --no-detach with myself, so that I can have a handle on the PID.
screenkey will gracefully shutdown on SIGINT or SIGTERM.

I'm not too fond of the default behavior to detach automatically, as it
creates some other "funky" problems for GTK itself, but it was there in
the original version so I kept it.
