### ISSUE TITLE
Replacing display of left and right key with cursor based natural behaviour like backspace

### ISSUE THREAD

**Issue by Zerokami** [wavexx/screenkey#54]
I want left and right keys to act like backspace. i.e if I press left I want the display cursor to go left and type from there. Like in a text editor or how the backspace works in Screenkey.

Please add this feature.

I want to build a tutorial using this and I some times make typos and I go left and right and it's annoying that instead of natural left and right behavior the keys are displayed

**Comment by wavexx** [comment]
This makes a lot of sense.
But just to be realistic, keep in mind we're just replicating blindly what a line editor would do, so it might not always replicate what the actual editor is doing (exactly like backspace is being processed now).

**Comment by wavexx** [comment]
Thinking out loud, it would almost make sense to create a full editing widget which is transparent to events and simply send whatever the user is doing. For example, a GtkEdit field without borders would in fact handle most of the input events as the user would expect (as the input map is essentially the same).

But of course, what happens when the timeout is reached? We clear the editor?
