### ISSUE TITLE
Print some help when initialization fails

### ISSUE THREAD

**Issue by caryoscelus** [wavexx/screenkey#56]
I had the same `Exception: Cannot initialize input method` problem as mentioned in #19 (the solution that worked for me was to run `ibus-daemon --xim`). I think it would be nice to print some short help message along with that error which would describe possible fixes or at least link to a page containing more info.

**Comment by wavexx** [comment]
I'll add a brief graphical message now. I know it's not enough, but many people simply remain baffled :/

Adding *online* help is something I'd want to add. And possibly some more descriptive tooltips (which is easier for contributors?).

Startup issues due to misconfigured input methods seems pretty frequent. Various distros do quite a poor job at patching user's profiles, often leaving conflicting settings. I've written quite a bit about those in the closed issues. I'd love if someone could go over the closed issues and collected some text to put in the readme. Even if's not perfect, it would be of a great help to speed things up.

**Comment by wavexx** [comment]
In the current master, this will displayed if initialization fails:

![2018-05-13t164804](https://user-images.githubusercontent.com/1017726/39968474-9009757e-56cd-11e8-8530-03c0d9962af6.png)

The link points to the "throubleshooting" section of the README, which doesn't exist yet.

**Comment by wavexx** [comment]
Ok, I added some troubleshooting documentation: https://www.thregr.org/~wavexx/software/screenkey/#troubleshooting (also in the README).
