### ISSUE TITLE
Cannot quit or stop screenkey

### ISSUE THREAD

**Issue by Snowman3456** [wavexx/screenkey#58]
Can't quit or stop `screenkey`.

Tried `sudo killall screenkey`

Nothing in the `--help` menu so far as I can tell.

*Ubuntu 17.10 (Wayland)*

**Comment by wavexx** [comment]
On Wed, Dec 20 2017, Enigma wrote:
> Can't quit or stop screenkey.
>
> Tried sudo killall screenkey
>
> Nothing in the --help menu so far as I can tell.

From the systray, there is a "quit" entry.

**Comment by Snowman3456** [comment]
@wavexx There is no systray item.

![tray](https://user-images.githubusercontent.com/4528283/34228958-94054a0c-e5a0-11e7-8632-b552a6fc7b5f.png)

**Comment by wavexx** [comment]
On Wed, Dec 20 2017, Enigma wrote:
> @wavexx There is no systray item.

Because you have no tray, or?
If you're using unity, you might need the python-appindicator package.

If not, start "screenkey -d" from the terminal and see if any
error message is printed.

Finally, "pkill -f screenkey" will kill screenkey (screenkey is part of
the arguments, the actual process name is just python).

Alternatively, use "screenkey --no-detach" to manage the pid manually.

**Comment by Enigma0** [comment]
There's got to be a way to kill it manually though right..?

**Comment by Snowman3456** [comment]
It's GNOME since unity died in 17.10. I'll open a new ticket for that.

```
$ ./screenkey -d
DEBUG:Screenkey:file /home/[USER]/.config/screenkey.json does not exists.
DEBUG:Screenkey:Restarting LabelManager.
DEBUG:Screenkey:Thread started.
DEBUG:Screenkey:Using StatusIcon.
```

`pkill -f screenkey` worked - thanks.
